name: corplink
description: CropLink app with Firebase (Auth, Firestore, Storage) and i18n (EN/SI/TA). No location/weather.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage:  ^13.0.1
  image_picker: ^1.2.0
  easy_localization: ^3.0.8
  intl: ^0.20.0
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
