// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN_XQxlzFVEKZuhnJXtUK_6DtbivL3AW4',
    appId: '1:172901475024:web:2086f05e3498e17055b4d5',
    messagingSenderId: '172901475024',
    projectId: 'croplink-ed268',
    authDomain: 'croplink-ed268.firebaseapp.com',
    storageBucket: 'croplink-ed268.firebasestorage.app',
    measurementId: 'G-SRPDNYVGKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC58AddTtiGWqtdcR4yvep9PcLuw5KZPgs',
    appId: '1:172901475024:android:1edf5beb9ae2b7bc55b4d5',
    messagingSenderId: '172901475024',
    projectId: 'croplink-ed268',
    storageBucket: 'croplink-ed268.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4FuIi0GNnUYr4ozvdebdXrPA-bh45NZw',
    appId: '1:172901475024:ios:eba985fb4479042055b4d5',
    messagingSenderId: '172901475024',
    projectId: 'croplink-ed268',
    storageBucket: 'croplink-ed268.firebasestorage.app',
    iosBundleId: 'com.yourcompany.corplink',
  );
}
